from collections.abc import Awaitable


def version() -> str: ...
def echo(msg: str) -> Awaitable[str]: ...


class WarpLLMNativeError(Exception): ...


class Client:
    def __init__(self, config_json: str) -> None: ...
    def chat_completion(self, request_json: str) -> str: ...
    def async_chat_completion(self, request_json: str) -> Awaitable[str]: ...
