//! Generates the language-level type hints from Rust's serialized boundary.
//!
//! This is a workspace tool, not a feature that writes files while testing the
//! published crate. It stages complete output directories and replaces them
//! only after every generator succeeds, so removed Rust types cannot linger.

use std::any::TypeId;
use std::collections::{BTreeMap, HashSet};
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use schemars::JsonSchema;
use schemars::generate::SchemaSettings;
use serde_json::{Value, json};
use ts_rs::{Config, TS, TypeVisitor};
use warpllm::OpenAiError;
use warpllm::protocol::openai_compat::chat_completions::types::{
    CreateChatCompletionRequest, CreateChatCompletionResponse, CreateChatCompletionStreamResponse,
};

fn main() {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("codegen crate lives under <workspace>/crates")
        .to_owned();
    let staging = root
        .join("target")
        .join(format!("binding-codegen-{}", std::process::id()));
    if staging.exists() {
        fs::remove_dir_all(&staging).expect("remove abandoned staging directory");
    }
    fs::create_dir_all(&staging).expect("create staging directory");

    generate_typescript(&staging.join("typescript"));
    generate_python(&root, &staging);

    replace_dir(
        &staging.join("typescript"),
        &root.join("bindings/node/src-ts/generated"),
    );
    replace_dir(
        &staging.join("python"),
        &root.join("bindings/python/python/warpllm/_generated"),
    );
    fs::remove_dir_all(&staging).expect("remove staging directory");
}

fn replace_dir(staged: &Path, destination: &Path) {
    if destination.exists() {
        fs::remove_dir_all(destination).expect("remove old generated directory");
    }
    fs::rename(staged, destination).expect("install generated directory");
}

fn generate_typescript(output: &Path) {
    fs::create_dir_all(output).expect("create TypeScript staging directory");
    let config = Config::new().with_large_int("number");
    let mut declarations = Declarations::new(config);
    declarations.collect::<CreateChatCompletionRequest>();
    declarations.collect::<CreateChatCompletionResponse>();
    declarations.collect::<CreateChatCompletionStreamResponse>();
    declarations.collect::<OpenAiError>();

    let mut source =
        String::from("// Generated by `cargo run -p warpllm-codegen`. Do not edit.\n\n");
    for (name, declaration) in &declarations.items {
        let mut declaration = declaration.clone();
        if name == "CreateChatCompletionRequest" {
            declaration = optionalize_request_model(&declaration);
        }
        source.push_str("export ");
        source.push_str(&declaration);
        source.push_str("\n\n");
    }
    fs::write(output.join("types.ts"), normalize_typescript(&source))
        .expect("write generated TypeScript");
}

/// The request's `model` field is a plain `String` carrying only
/// `#[serde(default)]` — ts-rs 12 refuses `#[ts(optional)]` on non-`Option`
/// fields, so there is no attribute that makes it emit `model?: string`. It
/// genuinely is optional at the wire (a body carrying only `models` must
/// deserialize), so the declaration is patched here rather than the Core API
/// churned to `Option<String>` for a codegen concern. Guarded to the
/// request's own declaration; satisfies checking the round-trip in tests.
fn optionalize_request_model(declaration: &str) -> String {
    declaration.replacen("model: string,", "model?: string,", 1)
}

fn normalize_typescript(source: &str) -> String {
    let lines = source.lines().map(str::trim_end).collect::<Vec<_>>();
    format!("{}\n", lines.join("\n").trim_end())
}

struct Declarations {
    config: Config,
    seen: HashSet<TypeId>,
    items: BTreeMap<String, String>,
}

impl Declarations {
    fn new(config: Config) -> Self {
        Self {
            config,
            seen: HashSet::new(),
            items: BTreeMap::new(),
        }
    }

    fn collect<T: TS + ?Sized + 'static>(&mut self) {
        if T::output_path().is_none() || !self.seen.insert(TypeId::of::<T>()) {
            return;
        }
        let name = T::ident(&self.config);
        let declaration = T::decl(&self.config);
        T::visit_dependencies(self);
        self.items.insert(name, declaration);
    }
}

impl TypeVisitor for Declarations {
    fn visit<T: TS + 'static + ?Sized>(&mut self) {
        self.collect::<T>();
    }
}

fn generate_python(root: &Path, staging: &Path) {
    let schema_dir = staging.join("schema");
    let output_dir = staging.join("python");
    fs::create_dir_all(&schema_dir).expect("create schema staging directory");
    fs::create_dir_all(&output_dir).expect("create Python staging directory");

    write_schema::<CreateChatCompletionRequest>(
        &schema_dir.join("request.json"),
        Contract::Deserialize,
    );
    write_schema::<CreateChatCompletionResponse>(
        &schema_dir.join("response.json"),
        Contract::Serialize,
    );
    write_schema::<CreateChatCompletionStreamResponse>(
        &schema_dir.join("stream_response.json"),
        Contract::Serialize,
    );
    write_schema::<OpenAiError>(&schema_dir.join("error.json"), Contract::Serialize);

    for (schema, output) in [
        ("request.json", "request.py"),
        ("response.json", "response.py"),
        ("stream_response.json", "stream_response.py"),
        ("error.json", "error.py"),
    ] {
        let python_project = root.join("bindings/python");
        let generator = if cfg!(windows) {
            python_project.join(".venv/Scripts/datamodel-codegen.exe")
        } else {
            python_project.join(".venv/bin/datamodel-codegen")
        };
        assert!(
            generator.exists(),
            "{} is missing; run `cd bindings/python && uv sync --locked` first",
            generator.display()
        );
        let status = Command::new(&generator)
            .current_dir(&python_project)
            .args([
                "--input-file-type",
                "jsonschema",
                "--output-model-type",
                "typing.TypedDict",
                "--target-python-version",
                "3.10",
                "--use-standard-collections",
                "--use-union-operator",
                "--disable-timestamp",
                "--enum-field-as-literal",
                "all",
                "--formatters",
                "builtin",
                "--input",
            ])
            .arg(schema_dir.join(schema))
            .arg("--output")
            .arg(output_dir.join(output))
            .status()
            .expect("run datamodel-codegen through uv");
        assert!(status.success(), "Python generation failed for {schema}");
    }

    fs::write(
        output_dir.join("__init__.py"),
        "\"\"\"Generated by `cargo run -p warpllm-codegen`. Do not edit.\"\"\"\n\
         \n\
         from .request import ChatCompletionRequestMessage, CreateChatCompletionRequest\n\
         from .response import CreateChatCompletionResponse\n\
         from .stream_response import CreateChatCompletionStreamResponse\n\
         \n\
         __all__ = [\n\
             \"ChatCompletionRequestMessage\",\n\
             \"CreateChatCompletionRequest\",\n\
             \"CreateChatCompletionResponse\",\n\
             \"CreateChatCompletionStreamResponse\",\n\
         ]\n",
    )
    .expect("write generated Python package");
}

#[derive(Clone, Copy)]
enum Contract {
    Serialize,
    Deserialize,
}

fn write_schema<T: JsonSchema>(path: &Path, contract: Contract) {
    let settings = match contract {
        Contract::Serialize => SchemaSettings::draft2020_12().for_serialize(),
        Contract::Deserialize => SchemaSettings::draft2020_12().for_deserialize(),
    };
    let schema = settings.into_generator().into_root_schema_for::<T>();
    let mut value = serde_json::to_value(schema).expect("serialize JSON Schema");
    if matches!(contract, Contract::Serialize) {
        strip_null_from_omitted_properties(&mut value);
    }
    nullable_as_any_of(&mut value);
    let mut rendered = serde_json::to_string_pretty(&value).expect("render JSON Schema");
    rendered.push('\n');
    fs::write(path, rendered).expect("write staged JSON Schema");
}

/// Set by an `Option<Option<T>>` field: one whose value is emitted as `null`
/// when it was received as `null`, and omitted only when it was absent. The
/// two states are the same Rust `Option` to schemars, so the field says which
/// it is and this marker is consumed here rather than shipped in the schema.
const NULLABLE_WHEN_PRESENT: &str = "x-nullable-when-present";

/// `Option<T>` accepts null while deserializing, but a field carrying
/// `skip_serializing_if = Option::is_none` is absent rather than null on output.
/// Schemars records optionality but retains the null branch, so remove it from
/// non-required properties when generating response/output types.
///
/// The exception is [`NULLABLE_WHEN_PRESENT`], which the Rust field marks
/// itself with.
fn strip_null_from_omitted_properties(value: &mut Value) {
    match value {
        Value::Object(map) => {
            let required: HashSet<String> = map
                .get("required")
                .and_then(Value::as_array)
                .into_iter()
                .flatten()
                .filter_map(Value::as_str)
                .map(str::to_owned)
                .collect();
            if let Some(Value::Object(properties)) = map.get_mut("properties") {
                for (name, property) in properties {
                    let nullable_when_present = property
                        .as_object_mut()
                        .is_some_and(|property| property.remove(NULLABLE_WHEN_PRESENT).is_some());
                    if !required.contains(name) && !nullable_when_present {
                        remove_null(property);
                    }
                }
            }
            for nested in map.values_mut() {
                strip_null_from_omitted_properties(nested);
            }
        }
        Value::Array(items) => items
            .iter_mut()
            .for_each(strip_null_from_omitted_properties),
        _ => {}
    }
}

fn remove_null(value: &mut Value) {
    let Value::Object(map) = value else {
        return;
    };
    if let Some(Value::Array(types)) = map.get_mut("type") {
        types.retain(|ty| ty != "null");
        if types.len() == 1 {
            let only = types[0].clone();
            map.insert("type".into(), only);
        }
    }
    let description = map.get("description").cloned();
    let Some(Value::Array(branches)) = map.get_mut("anyOf") else {
        return;
    };
    branches.retain(|branch| branch.get("type") != Some(&Value::String("null".into())));
    if branches.len() == 1 {
        let Some(mut only) = branches
            .pop()
            .and_then(|branch| branch.as_object().cloned())
        else {
            return;
        };
        if let Some(description) = description {
            only.entry("description").or_insert(description);
        }
        *map = only;
    }
}

/// datamodel-code-generator currently loses null from `type: [array, null]`.
/// `anyOf` is equivalent JSON Schema and is consumed correctly.
fn nullable_as_any_of(value: &mut Value) {
    match value {
        Value::Object(map) => {
            for nested in map.values_mut() {
                nullable_as_any_of(nested);
            }
            let Some(Value::Array(types)) = map.get("type") else {
                return;
            };
            if types.len() != 2 || !types.iter().any(|ty| ty == "null") {
                return;
            }
            let Some(concrete) = types.iter().find(|ty| *ty != "null").cloned() else {
                return;
            };
            let mut branch = map.clone();
            branch.insert("type".into(), concrete);
            branch.remove("description");
            let description = map.remove("description");
            map.clear();
            if let Some(description) = description {
                map.insert("description".into(), description);
            }
            map.insert(
                "anyOf".into(),
                json!([Value::Object(branch), { "type": "null" }]),
            );
        }
        Value::Array(items) => items.iter_mut().for_each(nullable_as_any_of),
        _ => {}
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn schema_for<T: JsonSchema>(contract: Contract) -> Value {
        let settings = match contract {
            Contract::Serialize => SchemaSettings::draft2020_12().for_serialize(),
            Contract::Deserialize => SchemaSettings::draft2020_12().for_deserialize(),
        };
        serde_json::to_value(settings.into_generator().into_root_schema_for::<T>()).unwrap()
    }

    fn assert_no_closed_string_constraints(value: &Value) {
        match value {
            Value::Object(map) => {
                assert!(!map.contains_key("const"), "unexpected const in {map:?}");
                assert!(!map.contains_key("enum"), "unexpected enum in {map:?}");
                map.values().for_each(assert_no_closed_string_constraints);
            }
            Value::Array(values) => values.iter().for_each(assert_no_closed_string_constraints),
            _ => {}
        }
    }

    #[test]
    fn omitted_output_properties_are_not_marked_nullable() {
        let mut schema = json!({
            "type": "object",
            "required": ["required_value"],
            "properties": {
                "required_value": { "type": ["string", "null"] },
                "optional_value": { "type": ["string", "null"] }
            }
        });

        strip_null_from_omitted_properties(&mut schema);

        assert_eq!(schema["properties"]["optional_value"]["type"], "string");
        assert_eq!(
            schema["properties"]["required_value"]["type"],
            json!(["string", "null"])
        );
    }

    /// The streaming shapes need the opposite of the rule above for the
    /// handful of fields a chunk sends as an explicit `null`, and they say so
    /// on the Rust field. The marker itself is codegen's, not the schema's.
    #[test]
    fn a_property_that_is_null_when_present_keeps_its_null() {
        let mut schema = json!({
            "type": "object",
            "required": [],
            "properties": {
                "usage": { "type": ["integer", "null"], "x-nullable-when-present": true },
                "system_fingerprint": { "type": ["string", "null"] }
            }
        });

        strip_null_from_omitted_properties(&mut schema);

        assert_eq!(
            schema["properties"]["usage"]["type"],
            json!(["integer", "null"])
        );
        assert!(
            schema["properties"]["usage"]
                .get(NULLABLE_WHEN_PRESENT)
                .is_none(),
            "the marker is consumed here, not shipped"
        );
        assert_eq!(schema["properties"]["system_fingerprint"]["type"], "string");
    }

    /// ...and end to end: the chunk's `usage` is absent OR null, while its
    /// `system_fingerprint` is only ever absent or a string.
    #[test]
    fn the_stream_response_tells_an_absent_field_from_a_null_one() {
        let mut schema = schema_for::<CreateChatCompletionStreamResponse>(Contract::Serialize);

        strip_null_from_omitted_properties(&mut schema);

        assert!(
            schema["properties"]["usage"]["anyOf"]
                .as_array()
                .unwrap()
                .iter()
                .any(|branch| branch["type"] == "null"),
            "usage lost the null it is sent with on every chunk but the last"
        );
        assert_eq!(
            schema["properties"]["system_fingerprint"]["type"], "string",
            "an absent-only field must not gain a null branch"
        );
    }

    #[test]
    fn nullable_array_rewrite_preserves_items() {
        let mut schema = json!({
            "type": ["array", "null"],
            "items": { "type": "integer" },
            "description": "numbers"
        });

        nullable_as_any_of(&mut schema);

        assert_eq!(schema["description"], "numbers");
        assert_eq!(schema["anyOf"][0]["type"], "array");
        assert_eq!(schema["anyOf"][0]["items"]["type"], "integer");
        assert_eq!(schema["anyOf"][1]["type"], "null");
    }

    #[test]
    fn compatibility_schemas_do_not_close_provider_defined_strings() {
        assert_no_closed_string_constraints(&schema_for::<CreateChatCompletionRequest>(
            Contract::Deserialize,
        ));
        assert_no_closed_string_constraints(&schema_for::<CreateChatCompletionResponse>(
            Contract::Serialize,
        ));
        assert_no_closed_string_constraints(&schema_for::<CreateChatCompletionStreamResponse>(
            Contract::Serialize,
        ));
    }

    #[test]
    fn typescript_uses_plain_strings_for_provider_defined_values() {
        let config = Config::new();
        let mut declarations = Declarations::new(config);
        declarations.collect::<CreateChatCompletionRequest>();
        declarations.collect::<CreateChatCompletionResponse>();
        let source = declarations
            .items
            .into_values()
            .collect::<Vec<_>>()
            .join("\n");

        for field in [
            "object: string",
            "service_tier?: string",
            "finish_reason: string",
            "role: string",
            "type: string",
        ] {
            assert!(source.contains(field), "missing `{field}` in:\n{source}");
        }
    }

    #[test]
    fn typescript_output_has_no_trailing_whitespace_or_extra_eof_lines() {
        assert_eq!(
            normalize_typescript("type A = { \n  x: string, \n};\n\n"),
            "type A = {\n  x: string,\n};\n"
        );
    }

    /// The single-model `model` field is optional TS (`model?: string`) even
    /// though the Rust field is a `String` — ts-rs cannot express that, so
    /// codegen patches it. Guards against the patch drifting when the field
    /// layout changes.
    #[test]
    fn request_model_is_optionalized_once() {
        let config = Config::new();
        let mut declarations = Declarations::new(config);
        declarations.collect::<CreateChatCompletionRequest>();

        let request = declarations
            .items
            .get("CreateChatCompletionRequest")
            .expect("request type collected")
            .clone();
        let patched = optionalize_request_model(&request);

        assert!(
            patched.starts_with("type CreateChatCompletionRequest = {"),
            "the patch targets the request declaration, got:\n{patched}"
        );
        assert!(
            patched.contains("model?: string,"),
            "expected optional model in:\n{patched}"
        );
        assert!(
            !patched.contains("model: string,"),
            "the required `model: string,` must be consumed:\n{patched}"
        );
        assert!(
            patched.contains("models?: Array<string> | null,"),
            "the models field must stay as-is:\n{patched}"
        );
    }
}
