#!/usr/bin/env python3
"""Regenerate the registry-derived docs snippets from the model registry.

The registry — `crates/warpllm/src/registry/specs.yaml` — is the single source
of truth for what warpllm can route to. This turns it into the tables the docs
render, so the published roster cannot drift from the shipped one.

Writes two snippets:

  docs/snippets/model-roster.mdx   every provider and model, with its limits
  docs/snippets/provider-keys.mdx  provider -> environment variable

Run it from anywhere:

    uv run --with pyyaml docs/scripts/gen_model_roster.py

It writes the snippets and prints nothing on success. `--check` writes nothing
and exits 1 if either is stale, which is what CI should run.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[2]
SPECS = REPO / "crates" / "warpllm" / "src" / "registry" / "specs.yaml"
SNIPPETS = REPO / "docs" / "snippets"

BANNER = (
    "{/* Generated by docs/scripts/gen_model_roster.py from\n"
    "    crates/warpllm/src/registry/specs.yaml. Do not edit by hand:\n"
    "    run `uv run --with pyyaml docs/scripts/gen_model_roster.py`. */}"
)

STREAM_API = "openai_compat_chat_completions_stream"


def thousands(value: int | None) -> str:
    return f"{value:,}" if value is not None else "—"


def upstream_name(model_key: str, spec: dict) -> str:
    """What warpllm sends on the wire. Defaults to the key's last segment."""
    return spec.get("model") or model_key.rsplit("/", 1)[-1]


def render_provider_keys(registry: dict) -> str:
    lines = [
        BANNER,
        "",
        "| Provider prefix | Environment variable | Base URL |",
        "| --- | --- | --- |",
    ]
    for provider, provider_spec in sorted(registry["providers"].items()):
        env_var = provider_spec.get("env_api_key")
        lines.append(
            f"| `{provider}/` "
            f"| {f'`{env_var}`' if env_var else '_none yet_'} "
            f"| `{provider_spec['base_url']}` |"
        )
    lines.append("")
    return "\n".join(lines)


def render_model_roster(registry: dict) -> str:
    lines = [BANNER, ""]
    for provider, provider_spec in sorted(registry["providers"].items()):
        env_var = provider_spec.get("env_api_key")
        key_cell = f"`{env_var}`" if env_var else "_not configurable yet_"
        lines += [
            f"### {provider}",
            "",
            f"Base URL `{provider_spec['base_url']}` &middot; API key {key_cell}",
            "",
            "| Model string | Sent upstream as | Context window | Max output | Streaming |",
            "| --- | --- | --- | --- | --- |",
        ]
        for model_key, model_spec in sorted(provider_spec["models"].items()):
            capabilities = model_spec.get("capabilities") or {}
            apis = {entry["api"] for entry in model_spec["supported_apis"]}
            lines.append(
                f"| `{model_key}` "
                f"| `{upstream_name(model_key, model_spec)}` "
                f"| {thousands(capabilities.get('max_input_tokens'))} "
                f"| {thousands(capabilities.get('max_output_tokens'))} "
                f"| {'Yes' if STREAM_API in apis else 'No'} |"
            )
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the snippet is out of date instead of rewriting it",
    )
    args = parser.parse_args()

    registry = yaml.safe_load(SPECS.read_text())
    rendered = {
        SNIPPETS / "model-roster.mdx": render_model_roster(registry),
        SNIPPETS / "provider-keys.mdx": render_provider_keys(registry),
    }

    stale = False
    for path, content in rendered.items():
        if args.check:
            if (path.read_text() if path.exists() else "") != content:
                print(
                    f"{path.relative_to(REPO)} is out of date; "
                    "run `uv run --with pyyaml docs/scripts/gen_model_roster.py`",
                    file=sys.stderr,
                )
                stale = True
        else:
            path.write_text(content)
    return 1 if stale else 0


if __name__ == "__main__":
    raise SystemExit(main())
