/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Client {
  constructor(configJson: string)
  chatCompletion(requestJson: string): Promise<string>
}

export declare function echo(msg: string): Promise<string>

export declare function version(): string
