/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class BalancedClient {
  constructor(configJson: string, candidatesJson: string)
  chatCompletions(requestJson: string): Promise<string>
  chatCompletionsStream(requestJson: string): Promise<ChatStream>
}

/**
 * A handle over one streamed reply. The iteration protocol is TypeScript's —
 * `client.ts` wraps this in `Symbol.asyncIterator` — because napi's own
 * `Generator` trait is synchronous and cannot express `for await`.
 */
export declare class ChatStream {
  /** The next chunk as JSON, or `null` once the stream ends. */
  next(): Promise<string | null>
}

export declare class Client {
  constructor(configJson: string)
  chatCompletions(requestJson: string): Promise<string>
  chatCompletionsStream(requestJson: string): Promise<ChatStream>
}

export declare function version(): string
